/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Usuario
 */
public class Bodega extends javax.swing.JFrame {

    /**
     * Creates new form Bodega
     */
    public Bodega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoEditarIng = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        txtIDingrediente = new javax.swing.JTextField();
        txtUnidadMedidaingrediente = new javax.swing.JTextField();
        txtCantidadingrediente = new javax.swing.JTextField();
        txtNombreingrediente = new javax.swing.JTextField();
        txtCostoingrediente = new javax.swing.JTextField();
        txtVencimientoingrediente = new javax.swing.JTextField();
        botonEditaringrediente = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BotonCancelaringrediente = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DialogoAgregarIng = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        txtIDingredienteAgregar = new javax.swing.JTextField();
        txtUnidadMedidaingredienteAgregar = new javax.swing.JTextField();
        txtCantidadingredienteAgregar = new javax.swing.JTextField();
        txtNombreingredienteAgregar = new javax.swing.JTextField();
        txtCostoingredienteAgregar = new javax.swing.JTextField();
        txtVencimientoingredienteAgregar = new javax.swing.JTextField();
        botonEditaringredienteAgregar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        BotonCancelaringredienteAgregar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PanelControlIngredientes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaIngredientes = new javax.swing.JTable();
        PanelCRUDIngredientes = new javax.swing.JPanel();
        BotonBuscarIngrediente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TXTbuscar1 = new javax.swing.JTextField();
        BotonEditarIngrediente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BotonElminarIngrediente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        BotonEditarIngrediente1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        txtIDingrediente.setBackground(new java.awt.Color(204, 255, 204));
        txtIDingrediente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "ID"));

        txtUnidadMedidaingrediente.setBackground(new java.awt.Color(204, 255, 204));
        txtUnidadMedidaingrediente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Unidad Medida"));

        txtCantidadingrediente.setBackground(new java.awt.Color(204, 255, 204));
        txtCantidadingrediente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cantidad"));
        txtCantidadingrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadingredienteActionPerformed(evt);
            }
        });

        txtNombreingrediente.setBackground(new java.awt.Color(204, 255, 204));
        txtNombreingrediente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Nombre"));
        txtNombreingrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreingredienteActionPerformed(evt);
            }
        });

        txtCostoingrediente.setBackground(new java.awt.Color(204, 255, 204));
        txtCostoingrediente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Costo"));

        txtVencimientoingrediente.setBackground(new java.awt.Color(204, 255, 204));
        txtVencimientoingrediente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Vencimiento"));

        botonEditaringrediente.setBackground(new java.awt.Color(102, 255, 204));
        botonEditaringrediente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Editar");

        javax.swing.GroupLayout botonEditaringredienteLayout = new javax.swing.GroupLayout(botonEditaringrediente);
        botonEditaringrediente.setLayout(botonEditaringredienteLayout);
        botonEditaringredienteLayout.setHorizontalGroup(
            botonEditaringredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonEditaringredienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botonEditaringredienteLayout.setVerticalGroup(
            botonEditaringredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonEditaringredienteLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        BotonCancelaringrediente.setBackground(new java.awt.Color(102, 255, 204));
        BotonCancelaringrediente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Cancelar");

        javax.swing.GroupLayout BotonCancelaringredienteLayout = new javax.swing.GroupLayout(BotonCancelaringrediente);
        BotonCancelaringrediente.setLayout(BotonCancelaringredienteLayout);
        BotonCancelaringredienteLayout.setHorizontalGroup(
            BotonCancelaringredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonCancelaringredienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        BotonCancelaringredienteLayout.setVerticalGroup(
            BotonCancelaringredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonCancelaringredienteLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidadMedidaingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCostoingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVencimientoingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonCancelaringrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditaringrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtIDingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCantidadingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(botonEditaringrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCancelaringrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnidadMedidaingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostoingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVencimientoingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
        );

        javax.swing.GroupLayout DialogoEditarIngLayout = new javax.swing.GroupLayout(DialogoEditarIng.getContentPane());
        DialogoEditarIng.getContentPane().setLayout(DialogoEditarIngLayout);
        DialogoEditarIngLayout.setHorizontalGroup(
            DialogoEditarIngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoEditarIngLayout.setVerticalGroup(
            DialogoEditarIngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoEditarIngLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        txtIDingredienteAgregar.setBackground(new java.awt.Color(204, 255, 204));
        txtIDingredienteAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "ID"));

        txtUnidadMedidaingredienteAgregar.setBackground(new java.awt.Color(204, 255, 204));
        txtUnidadMedidaingredienteAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Unidad Medida"));

        txtCantidadingredienteAgregar.setBackground(new java.awt.Color(204, 255, 204));
        txtCantidadingredienteAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cantidad"));
        txtCantidadingredienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadingredienteAgregarActionPerformed(evt);
            }
        });

        txtNombreingredienteAgregar.setBackground(new java.awt.Color(204, 255, 204));
        txtNombreingredienteAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Nombre"));
        txtNombreingredienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreingredienteAgregarActionPerformed(evt);
            }
        });

        txtCostoingredienteAgregar.setBackground(new java.awt.Color(204, 255, 204));
        txtCostoingredienteAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Costo"));

        txtVencimientoingredienteAgregar.setBackground(new java.awt.Color(204, 255, 204));
        txtVencimientoingredienteAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Vencimiento"));

        botonEditaringredienteAgregar.setBackground(new java.awt.Color(102, 255, 204));
        botonEditaringredienteAgregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("Agregar");

        javax.swing.GroupLayout botonEditaringredienteAgregarLayout = new javax.swing.GroupLayout(botonEditaringredienteAgregar);
        botonEditaringredienteAgregar.setLayout(botonEditaringredienteAgregarLayout);
        botonEditaringredienteAgregarLayout.setHorizontalGroup(
            botonEditaringredienteAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonEditaringredienteAgregarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botonEditaringredienteAgregarLayout.setVerticalGroup(
            botonEditaringredienteAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonEditaringredienteAgregarLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        BotonCancelaringredienteAgregar.setBackground(new java.awt.Color(102, 255, 204));
        BotonCancelaringredienteAgregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Cancelar");

        javax.swing.GroupLayout BotonCancelaringredienteAgregarLayout = new javax.swing.GroupLayout(BotonCancelaringredienteAgregar);
        BotonCancelaringredienteAgregar.setLayout(BotonCancelaringredienteAgregarLayout);
        BotonCancelaringredienteAgregarLayout.setHorizontalGroup(
            BotonCancelaringredienteAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonCancelaringredienteAgregarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel15)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        BotonCancelaringredienteAgregarLayout.setVerticalGroup(
            BotonCancelaringredienteAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonCancelaringredienteAgregarLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidadMedidaingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCostoingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVencimientoingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonCancelaringredienteAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditaringredienteAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtIDingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCantidadingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(botonEditaringredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCancelaringredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnidadMedidaingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostoingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVencimientoingredienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
        );

        javax.swing.GroupLayout DialogoAgregarIngLayout = new javax.swing.GroupLayout(DialogoAgregarIng.getContentPane());
        DialogoAgregarIng.getContentPane().setLayout(DialogoAgregarIngLayout);
        DialogoAgregarIngLayout.setHorizontalGroup(
            DialogoAgregarIngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogoAgregarIngLayout.setVerticalGroup(
            DialogoAgregarIngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoAgregarIngLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Unidad Medida", "Costo", "Vencimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaIngredientes);

        BotonBuscarIngrediente.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagen/buscar.png"))); // NOI18N
        jLabel5.setText(" ");

        javax.swing.GroupLayout BotonBuscarIngredienteLayout = new javax.swing.GroupLayout(BotonBuscarIngrediente);
        BotonBuscarIngrediente.setLayout(BotonBuscarIngredienteLayout);
        BotonBuscarIngredienteLayout.setHorizontalGroup(
            BotonBuscarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonBuscarIngredienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BotonBuscarIngredienteLayout.setVerticalGroup(
            BotonBuscarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonBuscarIngredienteLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BotonEditarIngrediente.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setText("Agregar");

        javax.swing.GroupLayout BotonEditarIngredienteLayout = new javax.swing.GroupLayout(BotonEditarIngrediente);
        BotonEditarIngrediente.setLayout(BotonEditarIngredienteLayout);
        BotonEditarIngredienteLayout.setHorizontalGroup(
            BotonEditarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonEditarIngredienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(33, 33, 33))
        );
        BotonEditarIngredienteLayout.setVerticalGroup(
            BotonEditarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonEditarIngredienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonElminarIngrediente.setBackground(new java.awt.Color(153, 153, 255));

        jLabel8.setText("Eliminar");

        javax.swing.GroupLayout BotonElminarIngredienteLayout = new javax.swing.GroupLayout(BotonElminarIngrediente);
        BotonElminarIngrediente.setLayout(BotonElminarIngredienteLayout);
        BotonElminarIngredienteLayout.setHorizontalGroup(
            BotonElminarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonElminarIngredienteLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(32, 32, 32))
        );
        BotonElminarIngredienteLayout.setVerticalGroup(
            BotonElminarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonElminarIngredienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonEditarIngrediente1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel7.setText("Editar");

        javax.swing.GroupLayout BotonEditarIngrediente1Layout = new javax.swing.GroupLayout(BotonEditarIngrediente1);
        BotonEditarIngrediente1.setLayout(BotonEditarIngrediente1Layout);
        BotonEditarIngrediente1Layout.setHorizontalGroup(
            BotonEditarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonEditarIngrediente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33))
        );
        BotonEditarIngrediente1Layout.setVerticalGroup(
            BotonEditarIngrediente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonEditarIngrediente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelCRUDIngredientesLayout = new javax.swing.GroupLayout(PanelCRUDIngredientes);
        PanelCRUDIngredientes.setLayout(PanelCRUDIngredientesLayout);
        PanelCRUDIngredientesLayout.setHorizontalGroup(
            PanelCRUDIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCRUDIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCRUDIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCRUDIngredientesLayout.createSequentialGroup()
                        .addComponent(TXTbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCRUDIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BotonEditarIngrediente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonElminarIngrediente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonEditarIngrediente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelCRUDIngredientesLayout.setVerticalGroup(
            PanelCRUDIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCRUDIngredientesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(PanelCRUDIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonBuscarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonEditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonElminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonEditarIngrediente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlIngredientesLayout = new javax.swing.GroupLayout(PanelControlIngredientes);
        PanelControlIngredientes.setLayout(PanelControlIngredientesLayout);
        PanelControlIngredientesLayout.setHorizontalGroup(
            PanelControlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelControlIngredientesLayout.createSequentialGroup()
                .addComponent(PanelCRUDIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelControlIngredientesLayout.setVerticalGroup(
            PanelControlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelControlIngredientesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(PanelControlIngredientesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(PanelCRUDIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelControlIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelControlIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadingredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadingredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadingredienteActionPerformed

    private void txtNombreingredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreingredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreingredienteActionPerformed

    private void txtCantidadingredienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadingredienteAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadingredienteAgregarActionPerformed

    private void txtNombreingredienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreingredienteAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreingredienteAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bodega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonBuscarIngrediente;
    private javax.swing.JPanel BotonCancelaringrediente;
    private javax.swing.JPanel BotonCancelaringredienteAgregar;
    private javax.swing.JPanel BotonEditarIngrediente;
    private javax.swing.JPanel BotonEditarIngrediente1;
    private javax.swing.JPanel BotonElminarIngrediente;
    private javax.swing.JDialog DialogoAgregarIng;
    private javax.swing.JDialog DialogoEditarIng;
    private javax.swing.JPanel PanelCRUDIngredientes;
    private javax.swing.JPanel PanelControlIngredientes;
    private javax.swing.JTextField TXTbuscar1;
    private javax.swing.JTable TablaIngredientes;
    private javax.swing.JPanel botonEditaringrediente;
    private javax.swing.JPanel botonEditaringredienteAgregar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCantidadingrediente;
    private javax.swing.JTextField txtCantidadingredienteAgregar;
    private javax.swing.JTextField txtCostoingrediente;
    private javax.swing.JTextField txtCostoingredienteAgregar;
    private javax.swing.JTextField txtIDingrediente;
    private javax.swing.JTextField txtIDingredienteAgregar;
    private javax.swing.JTextField txtNombreingrediente;
    private javax.swing.JTextField txtNombreingredienteAgregar;
    private javax.swing.JTextField txtUnidadMedidaingrediente;
    private javax.swing.JTextField txtUnidadMedidaingredienteAgregar;
    private javax.swing.JTextField txtVencimientoingrediente;
    private javax.swing.JTextField txtVencimientoingredienteAgregar;
    // End of variables declaration//GEN-END:variables
}
